### ISSUE TITLE
gRPC in a dll

### ISSUE THREAD

**Issue by mickagau** [thommyho/Cpp-gRPC-Windows-PreBuilts#1]
Hello Tommy
First of all thank you for this web site. 
Without it, i think i would have given up using gRPC with c++. Too boring to build (or indeed i am too lazy :)).

Nevertheless i would like to ask you if you could also build as a c++ dll.

The point is that according to architect point of view, some of them want to use REST and others gRPC.
For REST , i use cpprest package which comes with classical .dll, .h and lib.

Nowadays, when i build with gRPC, then all is in my own dll (including gRPC libs).

I think there are already part of the job done as i see grpc_csharp_ext.dll (but i don't know how to use it directly, even if this doable).

Would it be possible to build as a dll?

Thank you
Mickael

**Comment by thommyho** [comment]
Hi Michael,

thanks for the nice words. Glad it saved you time ;)

Sorry the delay. The notification went into SPAM directory :/.
I will try to build a custom version targeting x64 using vs2022 compiler.

But since ages I remember that officially gRPC-Community does not maintain / encourage to use shared libraries (dll's).
They mention several reasons here:
https://github.com/grpc/grpc/blob/master/BUILDING.md#windows-a-note-on-building-shared-libs-dlls

Let me check, 
I will report to you after the weekend.

Best regards,
Thomas

**Comment by thommyho** [comment]
Hi,
I have good and bad news :/
First the good, using cmake or conan (package-manager) build doesn't work, due to no support for shared libraries or linker erros for the crypto libraries.
But, I managed to build gRPC with vcpkg. In the image down below you can see, that it doesn't compile every library statically. 
**Sadly the gRPC is not a shared library** . I have a feeling für c++ they dropped (never really did) support the shared option.

![image](https://user-images.githubusercontent.com/29019959/219785428-f801c0a4-fc90-4e0e-bcd8-6f3f4e16fe7b.png)

If still interested in the vcpkg (also package manager)

Follow the installation steps: https://vcpkg.io/en/getting-started.html
Remark: You need at least 10-15GB space their. It creates a lot of intermediate files while building gRPC.
Install C++ Build-Toolchain for your VS-Studio of choice.

Then simply call:

_vcpkg install grpc:x64-windows_

After sucessful build, you can find all libraries in the vcpkg folder:

![image](https://user-images.githubusercontent.com/29019959/219786351-8f139828-e929-4aa7-8958-aeb32c775393.png)

Or I can forward you the test version.

Best regards, 
Thomas

PS: Another project: https://www.codeproject.com/Articles/5319700/Harlinn-Windows-A-Visual-Studio-2022-Solution
It uses gRPC dlls as well, but I don't know the version of gRPC.

![image](https://user-images.githubusercontent.com/29019959/219786682-48947cd2-d8c2-4718-99f2-18f4ad3bd886.png)

**Comment by thommyho** [comment]
I will close it for now. But @mickagau , feel free to re-open it.
